categories:
- Metagenomics
description: Suite for metabarcoding
long_description: |
  This is FROGS version 2.0.0 Galaxy Wrappers
  FROGS: Find Rapidly OTUs through Galaxy Solution 
  Authors:
  Valentin Marcon (valentin.marcon[a]inra.fr)
  Olivier Inizan  (olivier.inizan[a]inra.fr)
  Laure Quintric (laure.quintric[a]ifremer.fr)
  Patrick Durand (pgdurand[a]ifremer.fr)
  Maria Bernard (maria.bernard[a]inra.fr)
  Géraldine Pascal (geraldine.pascal[a]inra.fr)
name: frogs_2_0_0
#owner: oinizan #TestToolshed
owner: frogs #Toolshed
homepage_url: https://github.com/geraldinepascal/FROGS
remote_repository_url: https://github.com/oinizan/FROGS-wrappers
