categories:
- Metagenomics
description: Suite for metabarcoding
long_description: |
  This is FROGS version 3.2.1 Galaxy Wrappers
  FROGS: Find Rapidly OTUs through Galaxy Solution 
  FROGS is a workflow designed to produce an OTU count matrix from high depth sequencing amplicon data.
  Adviced : 
  reorder integrated_tool_panel.xml as indicated here : https://github.com/geraldinepascal/FROGS-wrappers#simplest-way
name: frogs
owner: oinizan #TestToolshed
homepage_url: https://github.com/geraldinepascal/FROGS-wrappers
remote_repository_url: https://github.com/geraldinepascal/FROGS-wrappers/tree/v3.2.1
